import type { Metadata } from "next";
import { AuthProvider } from "@/context/AppContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>  
          <div className="container">
            <div className="Header"><h1>Header</h1></div>
            <div className="Content">{children}</div>
            <div className="Footer"><h1>Footer</h1></div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
